### ISSUE TITLE
Remove custom Google Docs code

### ISSUE THREAD

**Issue by jonathanpeppers** [jonathanpeppers/inclusive-code-comments#42]
There is some odd code in:

* https://github.com/jonathanpeppers/inclusive-code-comments/blob/main/src/common/googleDocs.js
* https://github.com/jonathanpeppers/inclusive-code-comments/blob/main/src/common/googleSlides.js

It doesn't seem like we want any custom code for Google Docs. Let's just delete it?

We'll probably need to test it doesn't break anything -- and maybe check what happens in Google Docs. We probably don't even need the extension to show up at all in Google Docs, but it's OK if it happens to work.

**Comment by rachelkang** [comment]
started looking into this, and I'm seeing [`TweaksManager`](https://github.com/jonathanpeppers/inclusive-code-comments/blob/main/src/common/tweaksManager.js) has custom code for a _bunch_ of different services and websites. I'm assuming this exists because of most of these other sites have their own built-in spellchecker or some sort as well. 

I'm thinking we could delete most of these if not all of these as well, as GitHub isn't on there. But I was also thinking _maybe_ we can leave in the custom code that's there for things we use at Microsoft like office365 products? and maybe even dropbox? What do you think?

**Comment by jonathanpeppers** [comment]
I would just test Office365 or Dropbox -- and if the extension still works, maybe we could keep those.
